config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "resumes#new"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resume.rb
# frozen_string_literal: true

class Resume < ApplicationRecord
  validates :name, presence: true,
                   length: { minimum: 2 }
  has_one_attached :image

  def thumbnail
    image.variant(resize: '300x300!')
  end

  def banner
    image.variant(resize: '500x500!')
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/api/v1/sessions_controller.rb
# frozen_string_literal: true
module Api::V1
  class SessionsController < ApplicationController
    layout 'login'
    def new
      render 'new'
    end

    def create
      user = User.find_by_email(params[:email])
      if user&.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to new_resume_url, notice: 'Logged in'
      else
        flash.now[:alert] = 'Invalid email or password'
        render 'new'
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  # skip_before_filter :verify_authenticity_token
      
  def index
    resumes = Resume.order('created_at DESC')
    render json: {status: 'SUCCESS', message: 'Loaded resumes', data: resumes}, status: :ok
  end

  def show
    resume = Resume.find(params[:id])
    render json: {status: 'SUCCESS', message: 'Loaded resumes', data: resume}, status: :ok
  end

  def new
    @resume = Resume.new
  end

  def edit
    @resume = Resume.find(params[:id])
  end

  # POST request
  def create
    resume = Resume.new(resume_params)
    if resume.save
      render json: {status: 'SUCCESS', message: 'Saved resume', data: resume}, status: :ok
    else
      render json: {status: 'ERROR', message: 'Failed to save', data: resume.errors}, status: :unprocessable_entity
    end
  end

  def destroy
    resume = Resume.find(params[:id])
    if resume.destroy
      render json: {status: 'SUCCESS', message: 'Saved resume', data: resume}, status: :ok
    else
      render json: {status: 'ERROR', message: 'Saved resume', data: resume}, status: :ok
    end
  end

  def update
    @resume = Resume.find(params[:id])
    if @resume.update(resume_params)
      redirect_to @resume
    else
      render 'edit'
    end
  end

  private

  def resume_params
    params.permit(:name, :role, :contact_number, :email, :about, :image, :location, :country)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Hi there! Start building your CV...</h1>
<% if current_user %>
  <%= link_to 'Log Out', logout_path %>
<% else %>
  <%#= link_to 'Sign Up', new_user_path %>
  <%= link_to 'Log In', api_v1_login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cvbuilder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="bg-white div-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cvbuilder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg_login'>
    <%= yield %>
  </body>
</html>

app/views/resumes/edit.html.erb
<h1>Edit CV</h1>

<%= form_with(model: @resume, local: true) do |form| %>

  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@resume.errors.count, "error") %> prohibited
        this CV from being saved:
      </h2>
      <ul>
        <% @resume.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :your_name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :what_are_you? %><br>
    <%= form.text_field :role %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Cancel', resumes_path %>

app/views/resumes/index.html.erb
<table>
  <tr>
    <th>Created On</th>
    <th>Role</th>
    <th>Photo</th>
  </tr>
  <% @resumes.each do |resume| %>
    <tr>
      <td><%= resume.created_at %></td>
      <td><%= resume.role %></td>
      <td><%= link_to 'View', resume_path(resume) %></td>
      <td>
        <% if resume.image.attached? %>
          <%= image_tag resume.thumbnail %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/resumes/new.html.erb
<h1>SERENE MATHEW</h1>
<h3 class="highlight">Fullstack Engineer</h3>

<div class="container">
  <span>📞 +49 163 50 22 948</span>
  <span>📧 serene1990@gmail.com</span>
  <span>📍 Berlin, Germany</span>
</div>

<div class="main-container">
  <div class="item-details">
    <h2>SUMMARY</h2>
    <hr />
    <p>
      Software Engineer with experience in designing and building products in e-commerce and mobile space. Passionate about building APIs in Node.js, Ruby on Rails and front end using Javacript frameworks.
    </p>

    <h2>EXPERIENCE</h2>
    <hr />
    <h3>Fullstack Engineer</h3>
    <h4>TATA Consultancy Services</h4>
    <div>
      <span>02/2013 - 08/2019</span>
      <span>Kochi, India</span>
    </div>
    <p>
      Worked for different clients as a Fullstack engineer.
    </p>
    <ul>
      <li>
        TCS Fit4life - Engineered different web applications using Ruby on Rails which was used across the company for fitness initiatives.
      </li>
      <li>
        TCS Purpose4life - Built a web application using Ruby on Rails for CSR initiatives.
      </li>
      <li>
        Marks and Spencer (MnS) - Responsible for building scalable back end APIs using Ruby on Rails and Node.js, for Android mobile devices. Implemented scheduled jobs for the applications using Workers and Sidekiq, to be used in MnS store applications. Built customer facing front-end apps written in Angular.
      </li>
    </ul>

    <h3>Fullstack Engineer</h3>
    <h4>Babbel</h4>
    <div>
      <span>09/2019 - ongoing</span>
      <span>Berlin, Germany</span>
    </div>
    <p>
      Working as a Fullstack engineer, helping scale the language learning app to be used by everyone learning language. Part of the team responsible for the landing pages that help users convert to subscribers. Delivered apps written in Javascript, Ruby and hosted in AWS.
    </p>

    <h2>EDUCATION</h2>
    <hr />
    <h3>Bachelor of Engineering, Computer Science</h3>
    <div>
      <div>
        <h4>PSNA College of Engineering and Technology</h4>
        <div>
          <span>08/2008 - 05/2012</span>
          <span>Kochi, India</span>
        </div>
      </div>
      <div>
        <div>
          <span>GPA</span>
          <span>82.9 / 100</span>
        </div>
      </div>
    </div>
  </div>

  <div>
    <h2>EXPERTISE</h2>
    <hr />
    <div>
      <div>
        <span>
          Node.js
        </span>
        <span>
          🔵 🔵 🔵 🔵 ⚫️
        </span>
      </div>
      <div>
        <span>
          Ruby on Rails
        </span>
        <span>
          🔵 🔵 🔵 ⚫️ ⚫️
        </span>
      </div>
      <div>
        <span>
          Javascript
        </span>
        <span>
          🔵 🔵 🔵 🔵 🔵
        </span>
      </div>
      <div>
        <span>
          Ruby
        </span>
        <span>
          🔵 🔵 🔵 🔵 ⚫️
        </span>
      </div>
      <div>
        <span>
          React
        </span>
        <span>
          🔵 🔵 🔵 🔵 ⚫️
        </span>
      </div>
      <div>
        <span>
          Angular
        </span>
        <span>
          🔵 🔵 🔵 ⚫️ ⚫️
        </span>
      </div>
      <div>
        <span>
          AWS
        </span>
        <span>
          🔵 🔵 🔵 ⚫️ ⚫️
        </span>
      </div>
    </div>

    <h2>SKILLS</h2>
    <hr />
    <div>
      <span>HTML</span>
      <span>CSS</span>
      <span>Terraform</span>
      <span>CI / CD</span>
      <span>MySQL</span>
      <span>MongoDB</span>
      <span>Agile</span>
      <span>Figma</span>
    </div>

    <h2>FIND ME ONLINE</h2>
    <hr />
    <div>
      <span>
        🔗
      </span>
      <span>
        LinkedIn <br />
        serenematt
      </span>
    </div>
    <div>
      <span>
        🐈
      </span>
      <span>
        GitHub <br />
        serenematt
      </span>
    </div>
  </div>
</div>

app/views/resumes/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @resume.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @resume.role %>
</p>
<% if @resume.image.attached? %>
  <p>
    <strong>Photo:</strong>
    <%= image_tag @resume.banner %>
  </p>
<% end %>
<%= link_to 'List of CVs', resumes_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Create new CV', new_resume_path %>